name: CICD for Viesure Test challenge

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual Trigger'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  build:
    env:
      REPORT_PATH: target/allure-results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      #        run: |
      #          sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa
      #          sudo apt-get update
      #          sudo apt-get install firefox-trunk
      - name: Run Test with Firefox
        if: always()
        run: mvn clean test -Dspring.profiles.active=cicd-firefox
        continue-on-error: true

      - name: Run Test with Chrome
        if: always()
        run: mvn test -Dspring.profiles.active=cicd-chrome
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ REPORT_PATH }}
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.SECRET_ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history